### PR TITLE
Allow to register APISurface endpoints and handlers on an external HTTP server

### PR DESCRIPTION
**Pull request by clamoriniere1A**
This PR is implementing the proposal done in the issue: #32

### CODE REVIEW

**Comment by n3wscott** [comment]
LGTM

**Comment by clamoriniere1A** [comment]
@shawn-hurley right, I will add an unit-test.

**Comment by clamoriniere1A** [comment]
@shawn-hurley unit-test added

**Comment by pmorie** [comment]
Thanks for the patch @clamoriniere1A

**Pull request merged**
